# Generated by Django 3.0.5 on 2020-05-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200503_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(help_text='kjk', max_length=100),
        ),
    ]
